# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega', '0004_auto_20160819_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
